# Generated by Django 2.2.24 on 2024-02-09 18:26

from django.db import migrations

def update_new_building_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.filter(construction_year__lt=2005):
        flat.new_building = False
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(update_new_building_field),
    ]
