# Generated by Django 2.2.24 on 2024-02-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20240209_2132'),
        ('property', '0003_auto_20240209_2126'),
    ]

    operations = [
    ]
