# Generated by Django 2.2.24 on 2024-03-22 19:16

from django.db import migrations
import phonenumbers

def change_number_look(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats:
        number = flat.owners_phonenumber
        normal_number = phonenumbers.parse(number, 'RU')
        try:
            if phonenumbers.is_valid_number(normal_number):
                flat.owner_pure_phone = normal_number
            else:
                flat.owner_pure_phone = None
        except AttributeError:
            flat.owner_pure_phone = None
    Flat.objects.bulk_update(flats, ['owner_pure_phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20240402_2134'),
    ]

    operations = [
        migrations.RunPython(change_number_look)
    ]

