# Generated by Django 2.2.24 on 2024-04-04 12:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20240404_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200, verbose_name='ФИО владельца')),
                ('owner_number', models.CharField(max_length=20, verbose_name='Номер владельца')),
                ('owner_pure_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Нормал. номер владельца')),
                ('owner_flat', models.ManyToManyField(blank=True, related_name='onwers', to='property.Flat', verbose_name='Квартира')),
            ],
        ),
    ]
