# Generated by Django 2.2.24 on 2024-04-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20240406_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_flat',
            new_name='flat',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_number',
            new_name='pure_number',
        ),
    ]
