# Generated by Django 2.2.24 on 2024-04-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20240406_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flat',
            field=models.ManyToManyField(blank=True, related_name='owner', to='property.Flat', verbose_name='Квартира'),
        ),
    ]
