# Generated by Django 2.2.24 on 2024-04-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20240411_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='flat',
        ),
        migrations.AddField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, related_name='owners', to='property.Flat', verbose_name='Квартира'),
        ),
    ]
